language: php
sudo: required
dist: trusty
group: edge

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update

install:
  - sudo apt-get install make build-essential

before_script: git reset --hard
script: sudo ./install_x64.sh

